# quest 1


In [2]:
import numpy as np

In [17]:
a=np.array([[2,5],[4,8]])
type (a)
l=a.tolist()
print(l)
type(l)

[[2, 5], [4, 8]]


list

# quest2

method 1

In [19]:
a=np.array([[2,5,3],[4,8,5],[1,7,4]])
s=np.trace(a)
s

14

method 2


In [20]:
a=np.array([[2,5,3],[4,8,5],[1,7,4]])
d=np.diagonal(a)
s=0
for i in d:
    s=s+i
s

14

# quest2


In [23]:
a=np.array([[2,5,3],[4,8,5],[1,7,4]])
x=3
for i in range(len(a)):
    for j in range(len(a)):
        if a[i][j]>x:
            print ("this number is higher than 3:",a[i][j])
    

this number is higher than 3: 5
this number is higher than 3: 4
this number is higher than 3: 8
this number is higher than 3: 5
this number is higher than 3: 7
this number is higher than 3: 4


In [28]:
A=np.array([[2,5,3],[4,8,5],[1,7,4]])
B=np.array([[6,9,0],[4,9,1],[2,5,1]])
C=np.add(A,B)
C

array([[ 8, 14,  3],
       [ 8, 17,  6],
       [ 3, 12,  5]])

met1

In [35]:
A=np.array([[3,6,9],[12,3,9],[9,6,15]])
m=np.mean(A,axis=1)
m

array([ 6.,  8., 10.])

met2

In [41]:
a=np.array([[2,5,3],[4,8,5]])
sl1=0
sl2=0
for i in range(len(a)):
    if i == 0:
        for j in range(len(a[i])):
            sl1=sl1+a[i][j]
            ml1=sl1/len(a[i])
        print (m)
    else:
        for j in range(len(a[i])):
            sl2=sl2+a[i][j]
            ml2=sl2/len(a[i])
        print (ml1,"",ml2)
        

[ 6.  8. 10.]
3.3333333333333335  5.666666666666667
